### ISSUE TITLE
Tools Its not Working Correctly 

### ISSUE THREAD

**Issue by lbmaster23** [rvost/DayzServerTools#3]
The Tools its Not loading Category Value Flagas Usage Flags or Tags
![image](https://github.com/rvost/DayzServerTools/assets/51199528/17b2cec8-3861-4bee-aed0-1124a9714c14)

**Comment by rvost** [comment]
Can you please share your file (e.g. via [pastebin](https://pastebin.com/)) as I cannot reproduce the issue with any valid file.

P.S. Sorry for the late response.

**Comment by rvost** [comment]
I'll close the issue for now. Feel free to reopen it with more info.
